"""Canonical variable registry for resume template builder UI and validation."""

from __future__ import annotations

from app.models.resume_template_schemas import TemplateVariableDefinition

VARIABLE_REGISTRY: list[TemplateVariableDefinition] = [
    TemplateVariableDefinition(
        tag="{{profile.full_name}}",
        path="profile.full_name",
        label="Full name",
        group="Profile",
        description="Candidate full name from profile.",
    ),
    TemplateVariableDefinition(
        tag="{{profile.title}}",
        path="profile.title",
        label="Headline / title",
        group="Profile",
        description="Professional headline from profile.",
    ),
    TemplateVariableDefinition(
        tag="{{profile.email}}",
        path="profile.email",
        label="Email",
        group="Profile",
        description="Contact email.",
    ),
    TemplateVariableDefinition(
        tag="{{profile.phone}}",
        path="profile.phone",
        label="Phone",
        group="Profile",
        description="Formatted phone number.",
    ),
    TemplateVariableDefinition(
        tag="{{profile.linkedin}}",
        path="profile.linkedin",
        label="LinkedIn URL",
        group="Profile",
        description="LinkedIn profile URL.",
    ),
    TemplateVariableDefinition(
        tag="{{profile.github}}",
        path="profile.github",
        label="GitHub URL",
        group="Profile",
        description="GitHub profile URL.",
    ),
    TemplateVariableDefinition(
        tag="{{tailored.profile_summary}}",
        path="tailored.profile_summary",
        label="Tailored summary",
        group="Tailored content",
        description="AI-tailored profile summary for the job.",
    ),
    TemplateVariableDefinition(
        tag="{{PROFILE_SUMMARY}}",
        path="tailored.profile_summary",
        label="Tailored summary (legacy tag)",
        group="Legacy tags",
        description="Legacy alias for tailored summary.",
    ),
    TemplateVariableDefinition(
        tag="{{SKILLS_CONTENT}}",
        path="tailored.technical_skills",
        label="Skills block (legacy)",
        group="Legacy tags",
        description="Legacy skills placeholder expanded into multiple lines.",
    ),
    TemplateVariableDefinition(
        tag="{{#technical_skills}}",
        path="tailored.technical_skills",
        label="Skills loop open",
        group="Tailored content",
        description="Repeat block for skill categories.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{category}}",
        path="category",
        label="Skill category",
        group="Tailored content",
        description="Inside {{#technical_skills}} loop.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{skills}}",
        path="skills",
        label="Skill values",
        group="Tailored content",
        description="Inside {{#technical_skills}} loop.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{/technical_skills}}",
        path="",
        label="Skills loop close",
        group="Tailored content",
        description="Close skills repeat block.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{#work_experience}}",
        path="tailored.work_experience",
        label="Work experience loop open",
        group="Work experience",
        description="Repeat block cloned for each role.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{company_name}}",
        path="company_name",
        label="Company name",
        group="Work experience",
        description="Inside work experience loop.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{job_title}}",
        path="job_title",
        label="Job title",
        group="Work experience",
        description="Inside work experience loop.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{period}}",
        path="period",
        label="Employment period",
        group="Work experience",
        description="Formatted start/end dates.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{location}}",
        path="location",
        label="Role location",
        group="Work experience",
        description="Inside work experience loop.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{project_name}}",
        path="project_name",
        label="Project name",
        group="Work experience",
        description="Optional project label from tailored content.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{project_description}}",
        path="project_description",
        label="Project description",
        group="Work experience",
        description="Tailored project/body paragraph.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{#bullets}}",
        path="bullets",
        label="Bullets loop open",
        group="Work experience",
        description="Repeat bullet lines.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{bullet}}",
        path="bullet",
        label="Bullet text",
        group="Work experience",
        description="Single bullet inside bullets loop.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{/bullets}}",
        path="",
        label="Bullets loop close",
        group="Work experience",
        description="Close bullets repeat block.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{/work_experience}}",
        path="",
        label="Work experience loop close",
        group="Work experience",
        description="Close work experience repeat block.",
        repeatable=True,
    ),
    TemplateVariableDefinition(
        tag="{{job.company}}",
        path="job.company",
        label="Target company",
        group="Job context",
        description="Company for the job being tailored.",
    ),
    TemplateVariableDefinition(
        tag="{{job.title}}",
        path="job.title",
        label="Target job title",
        group="Job context",
        description="Title for the job being tailored.",
    ),
]


def list_template_variables() -> list[dict]:
    return [v.model_dump() for v in VARIABLE_REGISTRY]
