"""Add valid_jobs and invalid_jobs tables

Revision ID: ea7cdad5f94b
Revises: 
Create Date: 2026-01-31 15:01:06.490394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ea7cdad5f94b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_pattern_registry',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('domain_pattern', sa.String(length=255), nullable=False),
    sa.Column('api_endpoint_template', sa.Text(), nullable=True),
    sa.Column('json_ld_selector', sa.String(length=255), nullable=True),
    sa.Column('extraction_hints', sa.JSON(), nullable=True),
    sa.Column('priority', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Float(), nullable=True),
    sa.Column('success_rate', sa.Float(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('domain_pattern')
    )
    op.create_table('invalid_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('duplicate_of_job_id', sa.String(length=36), nullable=True),
    sa.Column('duplication_reason', sa.String(length=500), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('similarity_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_url'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index(op.f('ix_invalid_jobs_company'), 'invalid_jobs', ['company'], unique=False)
    op.create_index('ix_invalid_jobs_created_at', 'invalid_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_invalid_jobs_domain'), 'invalid_jobs', ['domain'], unique=False)
    op.create_index('ix_invalid_jobs_domain_company', 'invalid_jobs', ['domain', 'company'], unique=False)
    op.create_index('ix_invalid_jobs_duplicate_of', 'invalid_jobs', ['duplicate_of_job_id'], unique=False)
    op.create_index(op.f('ix_invalid_jobs_duplicate_of_job_id'), 'invalid_jobs', ['duplicate_of_job_id'], unique=False)
    op.create_index(op.f('ix_invalid_jobs_similarity_hash'), 'invalid_jobs', ['similarity_hash'], unique=False)
    op.create_table('job_extractions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='extractionstatus'), nullable=False),
    sa.Column('extraction_method', sa.Enum('API_JSON_LD', 'API_VENDOR', 'STATIC_HTML', 'BROWSER_RENDER', name='extractionmethod'), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=500), nullable=True),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('employment_type', sa.String(length=100), nullable=True),
    sa.Column('salary_range', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('responsibilities', sa.JSON(), nullable=True),
    sa.Column('requirements', sa.JSON(), nullable=True),
    sa.Column('benefits', sa.JSON(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('application_deadline', sa.DateTime(), nullable=True),
    sa.Column('remote_policy', sa.String(length=100), nullable=True),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('raw_html', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_url')
    )
    op.create_index('ix_job_extractions_created_at', 'job_extractions', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_extractions_domain'), 'job_extractions', ['domain'], unique=False)
    op.create_index('ix_job_extractions_domain_status', 'job_extractions', ['domain', 'status'], unique=False)
    op.create_index('ix_job_extractions_status', 'job_extractions', ['status'], unique=False)
    op.create_table('valid_jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('normalized_url', sa.String(length=2048), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=True),
    sa.Column('company', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_date', sa.DateTime(), nullable=True),
    sa.Column('experience_level', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=200), nullable=True),
    sa.Column('raw_metadata', sa.JSON(), nullable=True),
    sa.Column('similarity_hash', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('normalized_url'),
    sa.UniqueConstraint('source_url')
    )
    op.create_index(op.f('ix_valid_jobs_company'), 'valid_jobs', ['company'], unique=False)
    op.create_index('ix_valid_jobs_created_at', 'valid_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_valid_jobs_domain'), 'valid_jobs', ['domain'], unique=False)
    op.create_index('ix_valid_jobs_domain_company', 'valid_jobs', ['domain', 'company'], unique=False)
    op.create_index(op.f('ix_valid_jobs_similarity_hash'), 'valid_jobs', ['similarity_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_valid_jobs_similarity_hash'), table_name='valid_jobs')
    op.drop_index('ix_valid_jobs_domain_company', table_name='valid_jobs')
    op.drop_index(op.f('ix_valid_jobs_domain'), table_name='valid_jobs')
    op.drop_index('ix_valid_jobs_created_at', table_name='valid_jobs')
    op.drop_index(op.f('ix_valid_jobs_company'), table_name='valid_jobs')
    op.drop_table('valid_jobs')
    op.drop_index('ix_job_extractions_status', table_name='job_extractions')
    op.drop_index('ix_job_extractions_domain_status', table_name='job_extractions')
    op.drop_index(op.f('ix_job_extractions_domain'), table_name='job_extractions')
    op.drop_index('ix_job_extractions_created_at', table_name='job_extractions')
    op.drop_table('job_extractions')
    op.drop_index(op.f('ix_invalid_jobs_similarity_hash'), table_name='invalid_jobs')
    op.drop_index(op.f('ix_invalid_jobs_duplicate_of_job_id'), table_name='invalid_jobs')
    op.drop_index('ix_invalid_jobs_duplicate_of', table_name='invalid_jobs')
    op.drop_index('ix_invalid_jobs_domain_company', table_name='invalid_jobs')
    op.drop_index(op.f('ix_invalid_jobs_domain'), table_name='invalid_jobs')
    op.drop_index('ix_invalid_jobs_created_at', table_name='invalid_jobs')
    op.drop_index(op.f('ix_invalid_jobs_company'), table_name='invalid_jobs')
    op.drop_table('invalid_jobs')
    op.drop_table('api_pattern_registry')
    # ### end Alembic commands ###
