"""System prompts for AI-powered features."""

from app.prompts.cover_letter_prompt import (
    COVER_LETTER_INSTRUCTIONS,
    COVER_LETTER_PROMPT_MAX_LENGTH,
    COVER_LETTER_PROMPT_MIN_LENGTH,
)
from app.prompts.job_match_phase_a_prompt import (
    JOB_MATCH_PHASE_A_SYSTEM_PROMPT,
    JOB_MATCH_PHASE_A_USER_TEMPLATE,
)
from app.prompts.job_match_phase_b_prompt import (
    JOB_MATCH_PHASE_B_INSTRUCTIONS,
    JOB_MATCH_PHASE_B_OUTPUT_CONTRACT,
    JOB_MATCH_PHASE_B_SYSTEM_PROMPT,
    JOB_MATCH_PHASE_B_USER_TEMPLATE,
    RESUME_TAILORING_INSTRUCTIONS,
    RESUME_TAILORING_PROMPT_MAX_LENGTH,
    RESUME_TAILORING_PROMPT_MIN_LENGTH,
    build_phase_b_system_prompt,
)

__all__ = [
    "COVER_LETTER_INSTRUCTIONS",
    "COVER_LETTER_PROMPT_MAX_LENGTH",
    "COVER_LETTER_PROMPT_MIN_LENGTH",
    "JOB_MATCH_PHASE_A_SYSTEM_PROMPT",
    "JOB_MATCH_PHASE_A_USER_TEMPLATE",
    "JOB_MATCH_PHASE_B_INSTRUCTIONS",
    "JOB_MATCH_PHASE_B_OUTPUT_CONTRACT",
    "JOB_MATCH_PHASE_B_SYSTEM_PROMPT",
    "JOB_MATCH_PHASE_B_USER_TEMPLATE",
    "RESUME_TAILORING_INSTRUCTIONS",
    "RESUME_TAILORING_PROMPT_MAX_LENGTH",
    "RESUME_TAILORING_PROMPT_MIN_LENGTH",
    "build_phase_b_system_prompt",
]
